version: "3"

services:
  stllc:
    container_name: feeder
    build: .
    environment:
      PG_HOST: postgres
      PG_PORT: 5432
      PG_USER: postgres
      PG_PASS: postgres
      PG_DATABASE: postgres
      ADDR: ":8080"
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    container_name: postgres
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
    # networks:
    #   - development
    volumes:
      - ./postgres/pgdata:/var/lib/postgresql/data
        #    expose:
        #- "5432"
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres", "-d", "postgres"]
      interval: 3s
      timeout: 3s
      retries: 5

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes:
      - ./postgres/pgadmin:/var/lib/pgadmin
    ports:
      - "${PGADMIN_PORT:-5433}:80"
    # networks:
    #   - development
    depends_on:
      postgres:
        condition: service_healthy
# networks:
#   development:
#     driver: bridge
#
